### ISSUE TITLE
Uncaught Reference Error: jQuery is not defined 

### ISSUE THREAD

**Issue by lukemcdonald** [gravityplus/Gravity-Forms-Stripe#23]
When submitting a Gravity Form with AJAX enabled, if a validation error is thrown (e.g. submit blank form) the page is throwing a JS error, `Uncaught Reference Error: jQuery is not defined`. It appears there is a check in `stripe.php` where `$is_ajax` is being set to possibly check for this issue, though i'm not sure it's doing what it is suppose to; the `stripeResponseHandler` script is being inserted twice into the page.

Do you experience this problem?

**Comment by naomicbush** [comment]
No, I test validation errors all the time on a lot of sites. What version of GF are you using?

Although that sounds like a conflict with something else -- either the Gravity Forms JS or jQuery is not being enqueued properly.

Have you tried the troubleshooting steps?

**Comment by WebEndevSnippets** [comment]
I am getting the same error - 
"jQuery' is undefined 
flat-fee-mls-data-entry-form, line 63 character 675"

Also - the form will not submit in test mode using IE9. It errors out on the credit card field and displays the error "Invalid credit card number." 
I have tried several of the testing ccard numbers from here https://stripe.com/docs/testing , and they all error out.

I don't know if the jquery error is related to the "Invalid credit card number." error or not? 
Everything works fine in test mode in FF and Chrome.

This is a real problem because I cannot know if the form payment will work in IE when it is in live mode?

Please Help! :)

Version 1.7.2.2  of the plugin
WP 3.5.1
GF 1.7.2

Added: Here is line 63 from above:

 // if we are below the limit, make sure all checkboxes are available
else {
        this.prop('disabled', false);
 }

Oops, looks like line 63 ends with } from this:

// if we have reached or exceeded the limit, disable all other checkboxes
                        if(this.filter(':checked').length >= n) {
                            var unchecked = this.not(':checked');
                            unchecked.prop('disabled', true);
                        }

**Comment by frg004** [comment]
I've the same problem "ReferenceError: jQuery is not defined
JQuery(document).bind('gform_post_render', function () {"

Did someone find a way to fix this ? Thank you !

**Comment by WebEndevSnippets** [comment]
Yes, the latest version fixes it.
