### ISSUE TITLE
Cardholder name is allowed to be empty

### ISSUE THREAD

**Issue by admodiggity** [gravityplus/Gravity-Forms-Stripe#4]
The credit cardholder's name should be required, but the Stripe plugin will process if it is empty.

I guess Stripe doesn't really check against name?

**Comment by naomicbush** [comment]
The name is optional as Stripe only _attempts_ to verify the CVC and address - in addition to the card number and expiration date. According to their documentation on these fields, 

> "some banks do not support checking one or more of these parameters, in which case Stripe will return an 'unchecked' result. And depending on the bank, charges can succeed even when passed incorrect CVC and address information."

I currently don't even pass the name to the server which is why there's no validation check on it. I will consider passing it in just to "keep up appearances" I guess.

**Comment by admodiggity** [comment]
Wow, interesting.

I was wondering why your Stripe feed requires the address field (when Stripe doesn't).

Most of the Stripe payment forms I've seen to date only required name/cc#/expiration/cvc
